// Dummy POI data with coordinates around Lisbon area
export const poiData = [
  {
    id: 1,
    name: "Restaurante Ramiro",
    category: "restaurant",
    address: "Av. Almirante Reis 1, Lisbon",
    lat: 38.7287,
    lng: -9.1355,
    rating: 4.7,
  },
  {
    id: 2,
    name: "Time Out Market",
    category: "restaurant",
    address: "Av. 24 de Julho 49, Lisbon",
    lat: 38.7067,
    lng: -9.1447,
    rating: 4.5,
  },
  {
    id: 3,
    name: "Galp Gas Station",
    category: "gas_station",
    address: "Av. da República, Lisbon",
    lat: 38.7393,
    lng: -9.1464,
    rating: 4.0,
  },
  {
    id: 4,
    name: "Repsol Gas Station",
    category: "gas_station",
    address: "Avenida da Liberdade 203, Lisbon",
    lat: 38.7213,
    lng: -9.1482,
    rating: 4.1,
  },
  {
    id: 5,
    name: "Continente Supermarket",
    category: "supermarket",
    address: "Campo Grande, Lisbon",
    lat: 38.7573,
    lng: -9.1553,
    rating: 4.3,
  },
  {
    id: 6,
    name: "Pingo Doce",
    category: "supermarket",
    address: "Rua Castilho 64, Lisbon",
    lat: 38.7243,
    lng: -9.1527,
    rating: 4.2,
  },
  {
    id: 7,
    name: "Hotel Avenida Palace",
    category: "hotel",
    address: "Rua 1º de Dezembro 123, Lisbon",
    lat: 38.7158,
    lng: -9.1424,
    rating: 4.6,
  },
  {
    id: 8,
    name: "Tivoli Avenida Liberdade",
    category: "hotel",
    address: "Av. da Liberdade 185, Lisbon",
    lat: 38.7207,
    lng: -9.1469,
    rating: 4.7,
  },
  {
    id: 9,
    name: "Hospital da Luz",
    category: "hospital",
    address: "Av. Lusíada 100, Lisbon",
    lat: 38.7591,
    lng: -9.1792,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Centro Hospitalar Lisboa Norte",
    category: "hospital",
    address: "Av. Prof. Egas Moniz, Lisbon",
    lat: 38.7482,
    lng: -9.1607,
    rating: 4.2,
  },
  {
    id: 11,
    name: "Farmácia Alves",
    category: "pharmacy",
    address: "Praça Duque de Saldanha 1, Lisbon",
    lat: 38.7332,
    lng: -9.1444,
    rating: 4.3,
  },
  {
    id: 12,
    name: "Farmácia Andrade",
    category: "pharmacy",
    address: "Rua do Ouro 228, Lisbon",
    lat: 38.7097,
    lng: -9.1387,
    rating: 4.1,
  },
  {
    id: 13,
    name: "El Corte Inglés Parking",
    category: "parking",
    address: "Av. António Augusto de Aguiar, Lisbon",
    lat: 38.7341,
    lng: -9.1520,
    rating: 4.0,
  },
  {
    id: 14,
    name: "Martim Moniz Parking",
    category: "parking",
    address: "Praça Martim Moniz, Lisbon",
    lat: 38.7163,
    lng: -9.1360,
    rating: 3.8,
  },
  {
    id: 15,
    name: "Cervejaria Trindade",
    category: "restaurant",
    address: "R. Nova da Trindade 20, Lisbon",
    lat: 38.7118,
    lng: -9.1420,
    rating: 4.4,
  },
  {
    id: 16,
    name: "BP Gas Station",
    category: "gas_station",
    address: "Av. Infante Dom Henrique, Lisbon",
    lat: 38.7330,
    lng: -9.1230,
    rating: 3.9,
  },
  {
    id: 17,
    name: "Lidl",
    category: "supermarket",
    address: "Av. Almirante Reis 196, Lisbon",
    lat: 38.7370,
    lng: -9.1350,
    rating: 4.1,
  },
  {
    id: 18,
    name: "Hotel Mundial",
    category: "hotel",
    address: "Praça Martim Moniz 2, Lisbon",
    lat: 38.7154,
    lng: -9.1365,
    rating: 4.2,
  },
  {
    id: 19,
    name: "Hospital CUF Descobertas",
    category: "hospital",
    address: "R. Mário Botas, Lisbon",
    lat: 38.7580,
    lng: -9.0950,
    rating: 4.4,
  },
  {
    id: 20,
    name: "Farmácia Morais Sarmento",
    category: "pharmacy",
    address: "Av. de Roma 100, Lisbon",
    lat: 38.7470,
    lng: -9.1370,
    rating: 4.2,
  }
];