import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex justify-center items-center min-h-screen`}
      >
        {/* Phone Frame */}
        <div className="relative w-[430px] h-[900px] bg-no-repeat bg-center bg-contain flex items-center justify-center">
          <img
            src="/phone-frame.png"
            alt="Phone Frame"
            className="absolute top-0 left-0 w-full h-full pointer-events-none"
          />

          {/* Phone Screen (Inside the phone) */}
          <div className="w-[380px] h-[760px] bg-white rounded-2xl px-6 pt-20 pb-6 overflow-y-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
